language: ruby
bundler_args: --without production development test_utils
rvm:
  - 1.9.3
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rspec spec/
before_script:
  - mysql -e 'create database haynes_test'